pizza/urls.py
from django.urls import path
from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

pizzaria/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('endereco/', include('endereco.urls')),
    path('comentario/', include('comentario.urls')),
    path('avaliacao/', include('avaliacao.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    

]

#com essa configuração, quando clicar em uma imagem para abrir em uma nova guia, ela conseguirá abrir\
#em uma nova guia, independente de estar em uma página diferente.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/urls.py
from django.urls import path
from .views import ProdutoView, DetalheProduto

app_name = 'produto'

urlpatterns = [
    path('', ProdutoView.as_view(), name='lista'),
    path('<slug>', DetalheProduto.as_view(), name='detalhe'),

]

templates/parciais/_content.html
<session class="row my-1">
    <div class="col">
        <div class="container border">
          Conteudo  <i class="fa-brands fa-square-facebook" style="color: blue; font-size: 35px"></i>
        </div>
    </div>
</session>

templates/parciais/_footer.html
<!-- Footer -->
<div class="row fixed-bottom">
    <footer class="container-fluid py-5">
      <div class="container">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <ul class="list-inline text-center">		
              
              
              <!--{% if GITHUB %}-->
              <li class="list-inline-item">
                <a href="https://github.com/dcarll" target="blank">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <!--{% endif %}-->
              <li class="list-inline-item">
                <a href="https://www.linkedin.com/in/diego-carlos-da-silva/" target="blank">
                  <span class="fa-stack fa-lg">                  
                    <i style="font-size:48px;color:white">linkedin</i>
                  </span>
                </a>
              </li>
            </ul>
            <div class="small text-center text-muted fst-italic text-center">Copyright &copy; Blog v2 Diego 2022 {{GITHUB}}</div>
          </div>
        </div>
      </div>
    </footer> 
  </div>

templates/parciais/_header.html
<header class="row border mt-5">
	<div class="col">
		<h1><a href="/">Hearder</a></h1>
		<h1><a href="#"></a></h1>	
	</div>
</header>

templates/parciais/about.html
<section class="ftco-about d-md-flex">
    <div class="one-half img" style="background-image: url(images/about.jpg);"></div>
    <div class="one-half ftco-animate">
    <div class="heading-section ftco-animate ">
      <h2 class="mb-4">Welcome to <span class="flaticon-pizza">Pizza</span> A Restaurant</h2>
    </div>
    <div>
              <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.</p>
          </div>
    </div>
</section>

templates/parciais/carrossel.html
<section class="home-slider owl-carousel img" style="background-image: url(images/bg_1.jpg);">
    <div class="slider-item">
        <div class="overlay"></div>
      <div class="container">
        <div class="row slider-text align-items-center" data-scrollax-parent="true">

          <div class="col-md-6 col-sm-12 ftco-animate">
              <span class="subheading">Delicious</span>
            <h1 class="mb-4">Italian Cuizine</h1>
            <p class="mb-4 mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
            <p><a href="#" class="btn btn-primary p-3 px-xl-4 py-xl-3">Order Now</a> <a href="#" class="btn btn-white btn-outline-white p-3 px-xl-4 py-xl-3">View Menu</a></p>
          </div>
          <div class="col-md-6 ftco-animate">
              <img src="images/bg_1.png" class="img-fluid" alt="">
          </div>

        </div>
      </div>
    </div>

    <div class="slider-item">
        <div class="overlay"></div>
      <div class="container">
        <div class="row slider-text align-items-center" data-scrollax-parent="true">

          <div class="col-md-6 col-sm-12 order-md-last ftco-animate">
              <span class="subheading">Crunchy</span>
            <h1 class="mb-4">Italian Pizza</h1>
            <p class="mb-4 mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
            <p><a href="#" class="btn btn-primary p-3 px-xl-4 py-xl-3">Order Now</a> <a href="#" class="btn btn-white btn-outline-white p-3 px-xl-4 py-xl-3">View Menu</a></p>
          </div>
          <div class="col-md-6 ftco-animate">
              <img src="images/bg_2.png" class="img-fluid" alt="">
          </div>

        </div>
      </div>
    </div>

    <div class="slider-item" style="background-image: url(images/bg_3.jpg);">
        <div class="overlay"></div>
      <div class="container">
        <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

          <div class="col-md-7 col-sm-12 text-center ftco-animate">
              <span class="subheading">Welcome</span>
            <h1 class="mb-4">We cooked your desired Pizza Recipe</h1>
            <p class="mb-4 mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
            <p><a href="#" class="btn btn-primary p-3 px-xl-4 py-xl-3">Order Now</a> <a href="#" class="btn btn-white btn-outline-white p-3 px-xl-4 py-xl-3">View Menu</a></p>
          </div>

        </div>
      </div>
    </div>
  </section>

templates/parciais/container.html
<section class="container">
    <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section ftco-animate text-center">
        <h2 class="mb-4">Hot Pizza Meals</h2>
        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
      </div>
    </div>
    </div>
    <div class="container-wrap border">
        <div class="row no-gutters d-flex">
            <div class="col-lg-4 d-flex ftco-animate">
                <div class="services-wrap d-flex">
                    <a href="#" class="img" style="background-image: url(images/pizza-1.jpg);"></a>
                    <div class="text p-4">
                        <h3>Italian Pizza</h3>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia </p>
                        <p class="price"><span>$2.90</span> <a href="#" class="ml-2 btn btn-white btn-outline-white">Order</a></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 d-flex ftco-animate">
                <div class="services-wrap d-flex">
                    <a href="#" class="img" style="background-image: url(images/pizza-2.jpg);"></a>
                    <div class="text p-4">
                        <h3>Greek Pizza</h3>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                        <p class="price"><span>$2.90</span> <a href="#" class="ml-2 btn btn-white btn-outline-white">Order</a></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 d-flex ftco-animate">
                <div class="services-wrap d-flex">
                    <a href="#" class="img" style="background-image: url(images/pizza-3.jpg);"></a>
                    <div class="text p-4">
                        <h3>Caucasian Pizza</h3>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                        <p class="price"><span>$2.90</span> <a href="#" class="ml-2 btn btn-white btn-outline-white">Order</a></p>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 d-flex ftco-animate">
                <div class="services-wrap d-flex">
                    <a href="#" class="img order-lg-last" style="background-image: url(images/pizza-4.jpg);"></a>
                    <div class="text p-4">
                        <h3>American Pizza</h3>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia </p>
                        <p class="price"><span>$2.90</span> <a href="#" class="ml-2 btn btn-white btn-outline-white">Order</a></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 d-flex ftco-animate">
                <div class="services-wrap d-flex">
                    <a href="#" class="img order-lg-last" style="background-image: url(images/pizza-5.jpg);"></a>
                    <div class="text p-4">
                        <h3>Tomatoe Pie</h3>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                        <p class="price"><span>$2.90</span> <a href="#" class="ml-2 btn btn-white btn-outline-white">Order</a></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 d-flex ftco-animate">
                <div class="services-wrap d-flex">
                    <a href="#" class="img order-lg-last" style="background-image: url(images/pizza-6.jpg);"></a>
                    <div class="text p-4">
                        <h3>Margherita</h3>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                        <p class="price"><span>$2.90</span> <a href="#" class="ml-2 btn btn-white btn-outline-white">Order</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center mb-5 pb-3 mt-5 pt-5">
      <div class="col-md-7 heading-section text-center ftco-animate">
        <h2 class="mb-4">Our Menu Pricing</h2>
        <p class="flip"><span class="deg1"></span><span class="deg2"></span><span class="deg3"></span></p>
        <p class="mt-5">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
      </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-1.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Italian Pizza</span></h3>
                        <span class="price">$20.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-2.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Hawaiian Pizza</span></h3>
                        <span class="price">$29.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-3.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Greek Pizza</span></h3>
                        <span class="price">$20.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-4.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Bacon Crispy Thins</span></h3>
                        <span class="price">$20.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-5.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Hawaiian Special</span></h3>
                        <span class="price">$49.91</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-6.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Ultimate Overload</span></h3>
                        <span class="price">$20.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-7.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Bacon Pizza</span></h3>
                        <span class="price">$20.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-8.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Ham &amp; Pineapple</span></h3>
                        <span class="price">$20.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>

templates/parciais/footer.html
<footer class="">    
  <div class="container">
    <div class="row mb-12">
      <div class="col-lg-4 col-md-4 mb-3 mb-md-3">
        <div class="mb-4">
          <h2 class="text-white">About Us</h2>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          <ul class="float-md-left float-lft mt-2">
            <li>A asdsd</li>
            <li>dsçlkdsdk</li>      
          </ul>
        </div>
      </div>
      
      <div class="col-lg-4 col-md-4 mb-3 mb-md-3">
         <div class="mb-4 ml-md-4">
          <h2 class="text-white">Services</h2>
          <ul class="list-unstyled">
            <li><a href="#" class="py-2 d-block">Cooked</a></li>
            <li><a href="#" class="py-2 d-block">Deliver</a></li>
            <li><a href="#" class="py-2 d-block">Quality Foods</a></li>
            <li><a href="#" class="py-2 d-block">Mixed</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 mb-3 mb-md-3">
        <div class="mb-4">
            <h2 class="text-white">Have a Questions?</h2>
            <div class="mb-3">
              <ul>
                <li>203 Fake St. Mountain View, San Francisco, California, USA</li>
                <li><span>Telefone </span></li>
                <li>info@yourdomain.com</li>
              </ul>
            </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center text-white">
          Desevoldivo por diego
      </div>
    </div>
  </div>
</footer>

templates/parciais/galeria.html
<section class="ftco-gallery">
    <div class="container-wrap">
        <div class="row no-gutters">
                <div class="col-md-3 ftco-animate">
                    <a href="#" class="gallery img d-flex align-items-center" style="background-image: url(images/gallery-1.jpg);">
                        <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-search"></span>
                    </div>
                    </a>
                </div>
                <div class="col-md-3 ftco-animate">
                    <a href="#" class="gallery img d-flex align-items-center" style="background-image: url(images/gallery-2.jpg);">
                        <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-search"></span>
                    </div>
                    </a>
                </div>
                <div class="col-md-3 ftco-animate">
                    <a href="#" class="gallery img d-flex align-items-center" style="background-image: url(images/gallery-3.jpg);">
                        <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-search"></span>
                    </div>
                    </a>
                </div>
                <div class="col-md-3 ftco-animate">
                    <a href="#" class="gallery img d-flex align-items-center" style="background-image: url(images/gallery-4.jpg);">
                        <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-search"></span>
                    </div>
                    </a>
                </div>
    </div>
    </div>
</section>

templates/parciais/intro.html
<section class="ftco-intro">
    <div class="container-wrap">
        <div class="wrap d-md-flex">
            <div class="info">
                <div class="row no-gutters">
                    <div class="col-md-4 d-flex ftco-animate">
                        <div class="icon"><span class="icon-phone"></span></div>
                        <div class="text">
                            <h3>000 (123) 456 7890</h3>
                            <p>A small river named Duden flows</p>
                        </div>
                    </div>
                    <div class="col-md-4 d-flex ftco-animate">
                        <div class="icon"><span class="icon-my_location"></span></div>
                        <div class="text">
                            <h3>198 West 21th Street</h3>
                            <p>Suite 721 New York NY 10016</p>
                        </div>
                    </div>
                    <div class="col-md-4 d-flex ftco-animate">
                        <div class="icon"><span class="icon-clock-o"></span></div>
                        <div class="text">
                            <h3>Open Monday-Friday</h3>
                            <p>8:00am - 9:00pm</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="social d-md-flex pl-md-5 p-4 align-items-center">
                <ul class="social-icon">
          <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
          <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
          <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
        </ul>
            </div>
        </div>
    </div>
</section>

templates/parciais/nav.html
<nav class="navbar navbar-expand-lg ftco_navbar" id="ftco-navbar">
    <div class="container">
          <a class="navbar-brand" href="{% url 'produto:lista'%}"><span class=""><div class="nav-logo">Pizza<br>Delicous</div></span></a>
          <button class="navbar-toggler nav-font" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
          </button>
      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle nav-font" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Conta
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item " href="#">Login</a>
              <a class="dropdown-item" href="#">Cadastro</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Contato</a>
            </div>
            </li>
          <li>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0 nav-font" type="submit">Buscar</button>
            </form>     
          </li>               
          <li class="nav-item"><a href="menu.html" class="nav-link nav-font">Cardápio</a></li>
          <li class="nav-item"><a href="services.html" class="nav-link nav-font">Pedidos</a></li>
          <li class="nav-item"><a href="about.html" class="nav-link nav-font">Sobre</a></li>
          <li class="nav-item"><a href="contact.html" class="nav-link nav-font">Contato</a></li>
        </ul>
      </div>
      </div>
  </nav>

templates/parciais/pagination.html
{% if is_paginated %}

<div class="col mt-3 mb-3">
    <div class="row pagination justify-content-center">
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endif %}

templates/parciais/services.html
<section class="ftco-section ftco-services">
    <div class="overlay"></div>
    <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section ftco-animate text-center">
        <h2 class="mb-4">Our Services</h2>
        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
      </div>
    </div>
        <div class="row">
      <div class="col-md-4 ftco-animate">
        <div class="media d-block text-center block-6 services">
          <div class="icon d-flex justify-content-center align-items-center mb-5">
              <span class="flaticon-diet"></span>
          </div>
          <div class="media-body">
            <h3 class="heading">Healthy Foods</h3>
            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
          </div>
        </div>      
      </div>
      <div class="col-md-4 ftco-animate">
        <div class="media d-block text-center block-6 services">
          <div class="icon d-flex justify-content-center align-items-center mb-5">
              <span class="flaticon-bicycle"></span>
          </div>
          <div class="media-body">
            <h3 class="heading">Fastest Delivery</h3>
            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
          </div>
        </div>      
      </div>
      <div class="col-md-4 ftco-animate">
        <div class="media d-block text-center block-6 services">
          <div class="icon d-flex justify-content-center align-items-center mb-5"><span class="flaticon-pizza-1"></span></div>
          <div class="media-body">
            <h3 class="heading">Original Recipes</h3>
            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
          </div>
        </div>    
      </div>
    </div>
    </div>
</section>