pizza/urls.py
from django.urls import path
from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

pizzaria/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('endereco/', include('endereco.urls')),
    path('comentario/', include('comentario.urls')),
    path('avaliacao/', include('avaliacao.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    

]

#com essa configuração, quando clicar em uma imagem para abrir em uma nova guia, ela conseguirá abrir\
#em uma nova guia, independente de estar em uma página diferente.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/urls.py
from django.urls import path
from .views import ProdutoView, DetalheProduto

app_name = 'produto'

urlpatterns = [
    path('', ProdutoView.as_view(), name='lista'),
    path('<slug>', DetalheProduto.as_view(), name='detalhe'),

]

produto/models.py
from django.db import models
from django.conf import settings
import os
from PIL import Image
from django.utils.text import slugify
from utils import utils
from utils.base_class import Base

# Create your models here.

class Base(models.Model):
    criado = models.DateTimeField(auto_now_add=True)
    publicado = models.DateTimeField(auto_now=True)
    modificado = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Ingredientes(Base):
    nome = models.CharField(max_length=255)
    descricao = models.TextField(blank=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'ingrediente'
        verbose_name_plural = 'ingredientes'

class Pizza(Base):
    nome = models.CharField(max_length=255)
    desc_curta = models.CharField(max_length=255)
    desc_longa = models.TextField()
    ingredientes = models.ManyToManyField(Ingredientes, blank=True,)
    imagem = models.ImageField(upload_to='produto_imagens/%Y/%m', blank=True, null= True)
    slug = models.SlugField(unique=True, blank=True, null= True)
    preco_marketing = models.FloatField(verbose_name='Preço')
    preco_marketing_promocional = models.FloatField(verbose_name='Preço promo', default=0)
    tipo = models.CharField(default='V',
                            max_length=1,
                            choices=(
                                ('D', 'Doce'),
                                ('S', 'Salgada')
                            )
    )

    def get_preco_formatado(self):
        return utils.formata_preco(preco_marketing)
    get_preco_formatado.short_description='Preço'

    def get_preco_promocional_formatado(self):
        return utils.formata_preco(preco_marketing_promocional)
    get_preco_promocional_formatado.short_description = 'Preço promocional'

    @staticmethod
    def resize_image(img, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            img_pil.close()
            return

        new_height = round((new_width * original_height) / original_width)

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug
        
        super().save(*args, **kwargs)
        
        max_image_size = 800

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    def __str__(self):
        return self.nome
    

    

produto/views.py
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView, TemplateView
from .models import Pizza
# Create your views here.
class ProdutoView(ListView):
    model = Pizza
    paginate_by = 6
    context_object_name = 'produtos'
    template_name = 'produto/produtos.html'

class DetalheProduto(DetailView):
    model = Pizza
    context_object_name = 'produto'
    template_name = 'produto/detalhe.html'
    slug_url_kwarg = 'slug'

produto/templates/produto/detalhe.html
{% extends 'base.html'%}
{% block title %}
{{ produto.nome}}
{% endblock%}
{% block container %}
<section class="row justify-content-center">   
    <div class="col-lg-12">
        <div class="row justify-content-center">
            {% if produto.imagem %}
            <img class="img-fluid mt-5" src="{{ produto.imagem.url }}">
        {% endif %}
            <div class="row aling-content-center">
                <div class="col justify-content-center">
                    <h3><span>{{ produto.nome|linebreaks}}</span></h3><br>
                    <h4><span>{{ produto.desc_curta|linebreaks}}</span></h4>
                    <span class="price">{{produto.preco_marketing|linebreaks}}</span>
                </div>
            </hr>
                <p>{{ produto.desc_longa|linebreaks}}</p>         
            </div>
        </div>       
                     
                 
    </div>         
</section>
{% endblock %}

produto/templates/produto/produtos.html
{% extends 'base.html'%}
{% block title %}
    Pizzas
{% endblock %}

{% block container %}
<section class="container">
    

    <div class="row">
        <div class="col-lg-12">
            <div class="card-columns">
    
                {% for pizza in produtos %}
    
                <div class="card">
    
                    {% if pizza.imagem %}     

                    <a href="{% url 'produto:detalhe' pizza.slug %}">
                        <img class="card-img-top" src="{{ pizza.imagem.url }}" alt="{{ pizza.nome }}">
                    </a>
                    {% endif %}
    
                    <div class="card-body">
                        <h5 class="card-title">{{ pizza.nome }}</h5>
                        <p class="card-text">{{ pizza.desc_curta }}</p>
                        <div class="container product-price-block text-center">
    
                            {% if pizza.preco_marketing_promocional %}
                            <span class="product-price">
                                {{ pizza.preco_marketing_promocional}}
                            </span>
                            <span class="product-old-price text-muted">
                                {{ pizza.preco_marketing}}
                            </span>
                            {% else %}
                            <span class="product-price">
                                {{ pizza.preco_marketing}}
                            </span>
                            {% endif %}
    
                        </div>
                    </div>
                    <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            Pedir
                        </a>
                    </div>
                </div>
    
                {% endfor %}  
            </div>
        </div>
    </div>
    
    <div class="row mt-3">
        <div class="col">
            {% include 'parciais/pagination.html'%}

        </div>
    </div>

















    <div class="container">
        <div class="row justify-content-center mb-5 pb-3 mt-5 pt-5">
      <div class="col-md-7 heading-section text-center ftco-animate">
        <h2 class="mb-4">Our Menu Pricing</h2>
        <p class="flip"><span class="deg1"></span><span class="deg2"></span><span class="deg3"></span></p>
        <p class="mt-5">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
      </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-1.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Italian Pizza</span></h3>
                        <span class="price">$20.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-2.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Hawaiian Pizza</span></h3>
                        <span class="price">$29.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-3.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Greek Pizza</span></h3>
                        <span class="price">$20.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-4.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Bacon Crispy Thins</span></h3>
                        <span class="price">$20.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-5.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Hawaiian Special</span></h3>
                        <span class="price">$49.91</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-6.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Ultimate Overload</span></h3>
                        <span class="price">$20.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-7.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Bacon Pizza</span></h3>
                        <span class="price">$20.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
            <div class="pricing-entry d-flex ftco-animate">
                <div class="img" style="background-image: url(images/pizza-8.jpg);"></div>
                <div class="desc pl-3">
                    <div class="d-flex text align-items-center">
                        <h3><span>Ham &amp; Pineapple</span></h3>
                        <span class="price">$20.00</span>
                    </div>
                    <div class="d-block">
                        <p>A small river named Duden flows by their place and supplies</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    
</section>
{% endblock %}